datasets:
- TCGA-COADREAD
task_col: cancer_type_detailed
original_column: Cancer Type Detailed
extra_cols: []
task_type: classification
metrics:
- macro-ovr-auc
label_dict:
  0: Conventional_Adenocarcinoma
  1: Mucinous_Adenocarcinoma
sample_col: case_id
num_samples: 486
