datasets:
- TCGA-COADREAD
task_col: DSS_SURVIVAL
original_column: Disease-specific Survival status
original_time_column: Months of disease-specific survival
extra_cols:
- DSS_SURVIVAL_event
- DSS_SURVIVAL_days
task_type: survival
metrics:
- cindex
label_dict:
  0: time_bin_1_censored
  1: time_bin_2_censored
  2: time_bin_3_censored
  3: time_bin_4_censored
  4: time_bin_1_event
  5: time_bin_2_event
  6: time_bin_3_event
  7: time_bin_4_event
sample_col: case_id
num_samples: 432
