datasets:
- TCGA-NSCLC
task_col: n_stage
original_column: N Stage
extra_cols: []
task_type: classification
metrics:
- macro-ovr-auc
label_dict:
  0: Node_Negative
  1: Node_Positive
sample_col: case_id
num_samples: 879
