datasets:
- TCGA-BRCA
task_col: er_status
original_column: ER Status
extra_cols: []
task_type: classification
metrics:
- macro-ovr-auc
label_dict:
  0: ER_Negative
  1: ER_Positive
sample_col: case_id
num_samples: 679
