datasets:
- TCGA-BRCA
task_col: pr_status
original_column: PR Status
extra_cols: []
task_type: classification
metrics:
- macro-ovr-auc
label_dict:
  0: PR_Negative
  1: PR_Positive
sample_col: case_id
num_samples: 679
