datasets:
- TCGA-BRCA
task_col: tumor_type
original_column: Tumor Type
extra_cols: []
task_type: classification
metrics:
- macro-ovr-auc
label_dict:
  0: Infiltrating Ductal Carcinoma
  1: Infiltrating Lobular Carcinoma
  2: Special_Type
sample_col: case_id
num_samples: 860
