datasets:
- TCGA-STAD
task_col: molecular_subtype
original_column: Molecular Subtype
extra_cols: []
task_type: classification
metrics:
- macro-ovr-auc
label_dict:
  0: CIN
  1: GS
  2: MSI
  3: EBV
sample_col: case_id
num_samples: 246
